[package]
name = "widgets"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[features]
wgpu = ["iced_wgpu"]
opengl = ["iced_glow"]

[dependencies]
iced_native = { git="https://github.com/hecrj/iced", rev="d3b04bf892ce63d3129686968039c258945c5b02" }
iced_graphics = { git="https://github.com/hecrj/iced", rev="d3b04bf892ce63d3129686968039c258945c5b02" }

iced_wgpu = { git="https://github.com/hecrj/iced", rev="d3b04bf892ce63d3129686968039c258945c5b02", optional = true }
iced_glow = { git="https://github.com/hecrj/iced", rev="d3b04bf892ce63d3129686968039c258945c5b02", optional = true }
